
# Copyright 2018-2019 Leland Lucius
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from .Asynchronous_Notification_Disable_DM import *
from .Asynchronous_Notification_Enable_DM import *
from .Asynchronous_Notification_Query_DM import *
from .Authorization_List_Add import *
from .Authorization_List_Query import *
from .Authorization_List_Remove import *
from .Check_Authentication import *
from .Delete_ABEND_Dump import *
from .Directory_Manager_Local_Tag_Define_DM import *
from .Directory_Manager_Local_Tag_Delete_DM import *
from .Directory_Manager_Local_Tag_Query_DM import *
from .Directory_Manager_Local_Tag_Set_DM import *
from .Directory_Manager_Search_DM import *
from .Directory_Manager_Task_Cancel_DM import *
from .Event_Stream_Add import *
from .Event_Subscribe import *
from .Event_Unsubscribe import *
from .Image_Activate import *
from .Image_Active_Configuration_Query import *
from .Image_CPU_Define import *
from .Image_CPU_Define_DM import *
from .Image_CPU_Delete import *
from .Image_CPU_Delete_DM import *
from .Image_CPU_Query import *
from .Image_CPU_Query_DM import *
from .Image_CPU_Set_Maximum_DM import *
from .Image_Console_Get import *
from .Image_Create_DM import *
from .Image_Deactivate import *
from .Image_Definition_Async_Updates import *
from .Image_Definition_Create_DM import *
from .Image_Definition_Delete_DM import *
from .Image_Definition_Query_DM import *
from .Image_Definition_Update_DM import *
from .Image_Delete_DM import *
from .Image_Device_Dedicate import *
from .Image_Device_Dedicate_DM import *
from .Image_Device_Reset import *
from .Image_Device_Undedicate import *
from .Image_Device_Undedicate_DM import *
from .Image_Disk_Copy import *
from .Image_Disk_Copy_DM import *
from .Image_Disk_Create import *
from .Image_Disk_Create_DM import *
from .Image_Disk_Delete import *
from .Image_Disk_Delete_DM import *
from .Image_Disk_Query import *
from .Image_Disk_Share import *
from .Image_Disk_Share_DM import *
from .Image_Disk_Unshare import *
from .Image_Disk_Unshare_DM import *
from .Image_IPL_Delete_DM import *
from .Image_IPL_Query_DM import *
from .Image_IPL_Set_DM import *
from .Image_Lock_DM import *
from .Image_Lock_Query_DM import *
from .Image_MDISK_Link_Query import *
from .Image_Name_Query_DM import *
from .Image_Password_Set_DM import *
from .Image_Pause import *
from .Image_Query_Activate_Time import *
from .Image_Query_DM import *
from .Image_Recycle import *
from .Image_Replace_DM import *
from .Image_SCSI_Characteristics_Define_DM import *
from .Image_SCSI_Characteristics_Query_DM import *
from .Image_Status_Query import *
from .Image_Unlock_DM import *
from .Image_Volume_Add import *
from .Image_Volume_Delete import *
from .Image_Volume_Share import *
from .Image_Volume_Space_Define_DM import *
from .Image_Volume_Space_Query_DM import *
from .Image_Volume_Space_Define_Extended_DM import *
from .Image_Volume_Space_Query_Extended_DM import *
from .Image_Volume_Space_Remove_DM import *
from .Metadata_Get import *
from .Metadata_Set import *
from .Metadata_Space_Query import *
from .Name_List_Add import *
from .Name_List_Destroy import *
from .Name_List_Query import *
from .Name_List_Remove import *
from .Page_or_Spool_Volume_Add import *
from .Process_ABEND_Dump import *
from .Profile_Create_DM import *
from .Profile_Delete_DM import *
from .Profile_Lock_DM import *
from .Profile_Lock_Query_DM import *
from .Profile_Query_DM import *
from .Profile_Replace_DM import *
from .Profile_Unlock_DM import *
from .Prototype_Create_DM import *
from .Prototype_Delete_DM import *
from .Prototype_Name_Query_DM import *
from .Prototype_Query_DM import *
from .Prototype_Replace_DM import *
from .Query_ABEND_Dump import *
from .Query_All_DM import *
from .Query_API_Functional_Level import *
from .Query_Asynchronous_Operation_DM import *
from .Query_Directory_Manager_Level_DM import *
from .Response_Recovery import *
from .System_SCSI_Disk_Add import *
from .System_SCSI_Disk_Delete import *
from .System_SCSI_Disk_Query import *
from .Shared_Memory_Access_Add_DM import *
from .Shared_Memory_Access_Query_DM import *
from .Shared_Memory_Access_Remove_DM import *
from .Shared_Memory_Create import *
from .Shared_Memory_Delete import *
from .Shared_Memory_Query import *
from .Shared_Memory_Replace import *
from .SMAPI_Status_Capture import *
from .SSI_Query import *
from .Static_Image_Changes_Activate_DM import *
from .Static_Image_Changes_Deactivate_DM import *
from .Static_Image_Changes_Immediate_DM import *
from .System_Config_Syntax_Check import *
from .System_Disk_Accessibility import *
from .System_Disk_Add import *
from .System_Disk_IO_Query import *
from .System_Disk_Query import *
from .System_EQID_Query import *
from .System_FCP_Free_Query import *
from .System_Image_Performance_Query import *
from .Virtual_Network_OSA_Query import *
from .System_Information_Query import *
from .System_Page_Utilization_Query import *
from .System_Performance_Information_Query import *
from .System_Performance_Threshold_Enable import *
from .System_Performance_Threshold_Disable import *
from .System_RDR_File_Manage import *
from .System_RDR_File_Query import *
from .System_Service_Query import *
from .System_Shutdown import *
from .System_Spool_Utilization_Query import *
from .System_WWPN_Query import *
from .VMRELOCATE import *
from .VMRELOCATE_Image_Attributes import *
from .VMRELOCATE_Modify import *
from .VMRELOCATE_Status import *
from .VMRM_Configuration_Query import *
from .VMRM_Configuration_Update import *
from .VMRM_Measurement_Query import *
from .Virtual_Network_LAN_Access import *
from .Virtual_Network_LAN_Access_Query import *
from .Virtual_Network_LAN_Create import *
from .Virtual_Network_LAN_Delete import *
from .Virtual_Network_LAN_Query import *
from .Virtual_Network_OSA_Query import *
from .Virtual_Network_Vswitch_Create import *
from .Virtual_Network_Vswitch_Create_Extended import *
from .Virtual_Network_Vswitch_Delete import *
from .Virtual_Network_Vswitch_Delete_Extended import *
from .Virtual_Network_Vswitch_Query import *
from .Virtual_Network_Vswitch_Query_Byte_Stats import *
from .Virtual_Network_Vswitch_Query_Extended import *
from .Virtual_Network_Vswitch_Query_Stats import *
from .Virtual_Network_Vswitch_Set import *
from .Virtual_Network_Vswitch_Set_Extended import *

